name: 'Custom actions'
description: 'Custom action description'
inputs:
  say-hello: 
    description: 'Your name '
    required: true
    default: 'World'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Say Hello
      run: echo "Hello $NAME ........................ :) "
      shell: bash
      env:
        NAME: ${{ inputs.say-hello }}

    - name: Generate a random number
      id: random-number
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
