name: 'Custom actions'
description: 'Custom action description'
inputs:
  say-hello: 
    description: 'Your name '
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Say Hello
      run: echo "Hello $NAME ........................ :) "
      shell: bash
      env:
        NAME: ${{ inputs.say-hello }}
