name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: 
      matrix:
        target: [dev, acc, pro]
      url: https://github.com
    steps:
      - name: deploy
        run: | 
          sleep 5
          echo "Deployment completed successfully ..."